### PR TITLE
Adding Python 3.8 compatibility

### PR DESCRIPTION
**Pull request by slasyz**
Hello.

I tried to use impacket with Python 3.8 and there were two things I think we should fix.

1) There were a lot of warnings: `SyntaxWarning: "is" with a literal. Did you mean "=="?` To eliminate them, I replaced `is` to `==` in every `is b''`, `is ''` and `is ()` occurrence.

2) Parameter `digestmod` is now required, so I added `digestmod=hashlib.md5` to all `hmac.new()` calls without such parameter. This error was mentioned in #702 issue.

I haven't properly tested Python 3.8 compatibility yet, but I didn't find any errors for now.

Thank you.

### CODE REVIEW

**Comment by asolino** [comment]
Thanks for the PR @slasyz .. Gonna run a regression and will get back to you.

**Comment by asolino** [comment]
Tests passed ok, merging, thanks @slasyz!

**Comment by Torxed** [comment]
@asolino Could we perhaps get this into a release so that mirrors pointing towards the latest release can fetch this upstream. *(Specifically Arch Linux users have issues where Python3.8 is now the latest and greatest but the latest Impacket release don't support that yet)*.

**Comment by Torxed** [comment]
Still an issue in February. I wish I remembered how I fixed this..

**Comment by aancw** [comment]
Can't wait to see in release.

**Comment by asolino** [comment]
We're trying to push a new release in the next few weeks.

**Pull request merged**
