### PR TITLE
Adding silentcommand option

### PR DESCRIPTION
**Pull request by aconite33**
Added -silentcommand on to:

wmiexec.py
atexec.py
dcomexec.py

This allows users to run commands without executing a cmd.exe to run the command.

There is no output generate/presented to the user. This can help bypass blue team logging mechanisms looking for cmd.exe execution.

### CODE REVIEW

**Comment by aconite33** [comment]
@agsolino any chance of this getting merged? I'm running into alot of detections using the regular wmiexec/dcom/at because they are triggering of the redirects (Crowdstrike/Symantec/RedCloak/etc.).

**Comment by agsolino** [comment]
Hey @aconite33!
Just FYI, I'm not maintaining `impacket` myself actively anymore. Although I'll be committing code and still be active in the project (with less priority tho), the good friends at SecureAuth's Innovation Labs are taking over. (CC: @0xdeaddood).

**Comment by 0xdeaddood** [comment]
Hi @aconite33!
Let me check it and and I'll get back to you.

**Comment by aconite33** [comment]
@0xdeaddood Any update to this?

**Comment by stryker2k2** [comment]
@0xdeaddood and the SecureAuthCorp impacket Team.  This is an absolutely amazing tool!  With that said, I would ABSOLUTELY LOVE the ability to run wmiexec.py silently.  It seems that this merge request would be able to do just that!

Could the Team make this merge official?  Being able to call `wmiexec.py` with the `-silentcommand` would greatly benefit the community!

**Comment by 0xdeaddood** [comment]
> @0xdeaddood and the SecureAuthCorp impacket Team. This is an absolutely amazing tool! With that said, I would ABSOLUTELY LOVE the ability to run wmiexec.py silently. It seems that this merge request would be able to do just that!
> 
> Could the Team make this merge official? Being able to call `wmiexec.py` with the `-silentcommand` would greatly benefit the community!

Absolutely! This feature is great! I'm working on this. There are some conflicts in dcomexec and wmiexec that I'm resolving and testing. It will be included soon.

**Comment by stryker2k2** [comment]
> Absolutely! This feature is great! I'm working on this. There are some conflicts in dcomexec and wmiexec that I'm resolving and testing. It will be included soon.

Awesome!  You rock, @0xdeaddood!  We're looking forward to getting it in our hands!

**Comment by 0xdeaddood** [comment]
Hi @aconite33! 

I created a new [PR ](https://github.com/SecureAuthCorp/impacket/pull/1088)that includes your commits and solves the merging conflicts in `dcomexec.py` and `wmiexec.py` (the PR was a couple of commits behind master). Additionaly, I made some changes in `atexec.py`. I was having an issue when I tried to run the script with out the silent-command option. Could you please check it?

Thanks for your work!

**Comment by 0xdeaddood** [comment]
Merged in #1088. Thanks @aconite33, much appreciated!

**Pull request merged**
