### PR TITLE
Travis CI: Kick off TOX runs on all code submissions

### PR DESCRIPTION
**Pull request by cclauss**
This is on the __python36__ branch.

The repo switch would need to be turned on at:
* https://travis-ci.org/SecureAuthCorp or
* https://travis-ci.com/SecureAuthCorp

### CODE REVIEW

**Comment by cclauss** [comment]
Bump on this one?

**Comment by cclauss** [comment]
@asolino Do you have access rights to turn this on?  https://travis-ci.org/SecureAuthCorp/impacket

**Comment by asolino** [comment]
Here, https://travis-ci.com/SecureAuthCorp/impacket

Just merged https://github.com/SecureAuthCorp/impacket/pull/522 as a starting point. Please adjust this PR if you want to add extra functionality.

In any case.. the most important part is to enable the remote server test cases, which amounts the biggest code coverage.

**Comment by cclauss** [comment]
Closed in favor of #522 and #525

**Pull request closed without merging**
