### PR TITLE
Python 3.9: array.array().tostring() --> tobytes()

### PR DESCRIPTION
**Pull request by cclauss**
* https://docs.python.org/3/library/array.html#array.array.frombytes
* https://docs.python.org/3/library/array.html#array.array.tobytes
* https://docs.python.org/3/library/threading.html#threading.Thread.is_alive
* https://docs.python.org/3.9/whatsnew/3.9.html#removed Removed `.fromstring()`, `.tostring()`, `isAlive()`.

### CODE REVIEW

**Comment by cclauss** [comment]
https://www.python.org/downloads/release/python-390/

**Comment by meeuw** [comment]
Nice! (please note I'm *not* a maintainer of impacket)

This PR does a lot of code duplication, would it be a good idea to introduce compatibility functions for `tobytes` and `frombytes` which is initialized according to availability?

Something like:
```python
if hasattr(array.array, 'frombytes'):
   def frombytes(a, b):
       return a.frombytes(b)
else:
   def frombytes(a, b):
        return a.fromstring(b)
```

**Comment by cclauss** [comment]
It would be nicer to just drop support for Python 2 like everyone else has done and this problem disappears.

**Comment by meeuw** [comment]
FYI, Python 3.9 support has been added in #1054

**Pull request closed without merging**
