### PR TITLE
Implementation of RPC over HTTP v2

### PR DESCRIPTION
**Pull request by mohemiv**
Hello there,

It's a partial implementation of RPC over HTTP v2 protocol. Any chance you can review this?

### CODE REVIEW

**Comment by asolino** [comment]
Hey @mohemiv 

Thanks a lot for the PR! Have been wanting to add this functionality for quite some time. We will take a look at this for sure. There are many changes in here so bear with us until we extensively test it. 

It would be great to add some test cases to include when running `tox`

**Comment by 0xdeaddood** [comment]
Hi @mohemiv! 

I just finished reviewing the PR and running some tests, nice job! The rpcmap.py and rpcdump.py examples work great!
Just a couple of things, I get an error in two examples scripts (related with the regexps changes):
- getPac.py (line 309): "options.target" don't exist, it should be "options.credentials".
- raiseChild.py (line 1271):  you forgot to remove the variable "address".

Could you please modify these lines?
Thanks!!

**Comment by mohemiv** [comment]
Hi 0xdeaddood,

I'm glad to hear you've found suitable this code for the project. Changes are done, no problem.

**Comment by asolino** [comment]
Thanks a lot @mohemiv for this PR, big one! Merging!

**Pull request merged**
