### PR TITLE
Fix incorrect checkum regarding aes-encrypted TGS tickets

### PR DESCRIPTION
**Pull request by Fist0urs**
Hi,

checksum for TGS tickets regarding AES encryption is not at the same position as with RC4-HMAC (first 16 bytes). Using AES, the last 12 bytes represent the checksum.

I've also adapted the output hash format: unlike with RC4-HMAC, user and domain are mandatory here (as they are used as salt), so I've enclosed them within '$'. The optional part (between '*') will be the SPNs.

I've implemented the formats in hashcat, I'll PR them in the next few days, after a bit of code cleaning :)

Cheers!

### CODE REVIEW

**Comment by asolino** [comment]
Hey @Fist0urs Thanks for the PR.

@elitest, since you've added the AES stuff, your input on this PR would be appreciated. AFAIK this functionality was working correctly.

**Comment by asolino** [comment]
Hey @Fist0urs 

I went thru all the tickets referenced and now I understand things better. Merging PR, thanks!

**Comment by elitest** [comment]
lol I was just going to comment, but you beat me to it.  LGTM. thanks @Fist0urs!

**Comment by Fist0urs** [comment]
My pleasure! Thanks for your awesome work!

**Pull request merged**
