### PR TITLE
Fix nrpc to work for python 3

### PR DESCRIPTION
**Pull request by BarakSilverfort**
NRPC fails in python 3, there are a few issues:
1. Using str instead of bytes in hashlib:
md5 = hashlib.new('md5')
md5.update(\x00'*4)
2. using str to get bytes which fails:
md5.update(str(authSignature)[:8])
3. using ord on in int while iterating over bytes(ints)
chr(ord(i) ^ 0xf0)

### CODE REVIEW

**Comment by asolino** [comment]
Hey @BarakSilverfort thanks for the PR. Can you send me a repro code so I can add that to the [NRPC test cases](https://github.com/SecureAuthCorp/impacket/blob/master/tests/SMB_RPC/test_nrpc.py). Currently the methods you modified do not have test cases and that's why it's failing on Python3.

**Comment by BarakSilverfort** [comment]
Hey, this is the code we use that caused the error:
`        
        request = nrpc.NetrLogonSamLogonEx()
        request['LogonServer'] = "\x00"
        request['ComputerName'] = self.server_name + '\x00'
        request['LogonLevel'] = nrpc.NETLOGON_LOGON_INFO_CLASS.NetlogonInteractiveInformation
        request['LogonInformation']['tag'] = nrpc.NETLOGON_LOGON_INFO_CLASS.NetlogonInteractiveInformation
        request['LogonInformation']['LogonInteractive']['Identity']['LogonDomainName'] = self.netbios_domain_name
        request['LogonInformation']['LogonInteractive']['Identity'][
            'ParameterControl'] = 2 + 2 ** 14 + 2 ** 7 + 2 ** 9 + 2 ** 5 + 2 ** 11
        request['LogonInformation']['LogonInteractive']['Identity']['UserName'] = user_name
        request['LogonInformation']['LogonInteractive']['Identity']['Workstation'] = self.server_name

        user_enc_nthash = ARC4.new(self.session_key).encrypt(user_nthash)
        request['LogonInformation']['LogonInteractive']['LmOwfPassword'] = user_enc_nthash
        request['LogonInformation']['LogonInteractive']['NtOwfPassword'] = user_enc_nthash
        request['ValidationLevel'] = nrpc.NETLOGON_VALIDATION_INFO_CLASS.NetlogonValidationSamInfo4
        request['ExtraFlags'] = 0
        res = self.dce.request(request)
`

**Comment by asolino** [comment]
Hey @BarakSilverfort .. I cannot reproduce the issue. Just adapted your code to be able to run it:
```Python
import sys

from impacket.dcerpc.v5 import nrpc
from impacket.structure import hexdump
from Cryptodome.Cipher import ARC4

print(sys.version_info)

server_name='UNKNOWN'
netbios_domain_name = 'NETBIOS'
user_name = 'Administrator'
session_key = b"A"*8
user_nthash = (b'A'*16)

request = nrpc.NetrLogonSamLogonEx()
request['LogonServer'] = "\x00"
request['ComputerName'] = server_name + '\x00'
request['LogonLevel'] = nrpc.NETLOGON_LOGON_INFO_CLASS.NetlogonInteractiveInformation
request['LogonInformation']['tag'] = nrpc.NETLOGON_LOGON_INFO_CLASS.NetlogonInteractiveInformation
request['LogonInformation']['LogonInteractive']['Identity']['LogonDomainName'] = netbios_domain_name
request['LogonInformation']['LogonInteractive']['Identity'][
'ParameterControl'] = 2 + 2 ** 14 + 2 ** 7 + 2 ** 9 + 2 ** 5 + 2 ** 11
request['LogonInformation']['LogonInteractive']['Identity']['UserName'] = user_name
request['LogonInformation']['LogonInteractive']['Identity']['Workstation'] = server_name

user_enc_nthash = ARC4.new(session_key).encrypt(user_nthash)
request['LogonInformation']['LogonInteractive']['LmOwfPassword'] = user_enc_nthash
request['LogonInformation']['LogonInteractive']['NtOwfPassword'] = user_enc_nthash
request['ValidationLevel'] = nrpc.NETLOGON_VALIDATION_INFO_CLASS.NetlogonValidationSamInfo4
request['ExtraFlags'] = 0

request.dump()
hexdump(request.getData())
```
output:
```
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
NetrLogonSamLogonEx 
LogonServer:                     '\x00' 
ComputerName:                    'UNKNOWN\x00' 
LogonLevel:                      NetlogonInteractiveInformation 
LogonInformation:               
    tag:                             1 
    LogonInteractive:               
        Identity:                       
            LogonDomainName:                 'NETBIOS' 
            ParameterControl:                19106 
            Reserved:                       
                LowPart:                         0 
                HighPart:                        0 
            UserName:                        'Administrator' 
            Workstation:                     'UNKNOWN' 
        LmOwfPassword:                  
            Data:                            b'\x83\x8a\xa7|\x81\xe2\x8c\xe0\xfb\xea(\x1d\xa5\xb1tj' 
        NtOwfPassword:                  
            Data:                            b'\x83\x8a\xa7|\x81\xe2\x8c\xe0\xfb\xea(\x1d\xa5\xb1tj' 
ValidationLevel:                 NetlogonValidationSamInfo4 
ExtraFlags:                      0 


 0000   94 14 00 00 01 00 00 00  00 00 00 00 01 00 00 00   ................
 0010   00 00 AA AA BD C6 00 00  08 00 00 00 00 00 00 00   ................
 0020   08 00 00 00 55 00 4E 00  4B 00 4E 00 4F 00 57 00   ....U.N.K.N.O.W.
 0030   4E 00 00 00 01 00 01 00  B3 E7 00 00 0E 00 0E 00   N...............
 0040   36 DA 00 00 A2 4A 00 00  00 00 00 00 00 00 00 00   6....J..........
 0050   1A 00 1A 00 C5 5A 00 00  0E 00 0E 00 25 76 00 00   .....Z......%v..
 0060   83 8A A7 7C 81 E2 8C E0  FB EA 28 1D A5 B1 74 6A   ...|......(...tj
 0070   83 8A A7 7C 81 E2 8C E0  FB EA 28 1D A5 B1 74 6A   ...|......(...tj
 0080   07 00 00 00 00 00 00 00  07 00 00 00 4E 00 45 00   ............N.E.
 0090   54 00 42 00 49 00 4F 00  53 00 AB AB 0D 00 00 00   T.B.I.O.S.......
 00a0   00 00 00 00 0D 00 00 00  41 00 64 00 6D 00 69 00   ........A.d.m.i.
 00b0   6E 00 69 00 73 00 74 00  72 00 61 00 74 00 6F 00   n.i.s.t.r.a.t.o.
 00c0   72 00 AB AB 07 00 00 00  00 00 00 00 07 00 00 00   r...............
 00d0   55 00 4E 00 4B 00 4E 00  4F 00 57 00 4E 00 06 00   U.N.K.N.O.W.N...
 00e0   00 00 00 00                                        ....

Process finished with exit code 0
```

**Comment by BarakSilverfort** [comment]
I've went over the source code again, we are getting the errors from the flow that reaches nrpc.SEAL.
I think that the missing lines to reach it are:
`       self.dce.set_auth_type(RPC_C_AUTHN_NETLOGON)
         self.dce.set_auth_level(RPC_C_AUTHN_LEVEL_PKT_PRIVACY)
`

**Comment by asolino** [comment]
Thanks for the answer @BarakSilverfort . Just merged your PR + some additions. Please let me know if it is wokring on your side.

**Pull request merged**
