### PR TITLE
Adding Shadow Credentials attack to ntlmrelayx

### PR DESCRIPTION
**Pull request by ShutdownRepo**
Added [PyWhisker](https://github.com/ShutdownRepo/pywhisker)'s add feature to ntlmrelayx.
More info on [The Hacker Recipes](https://www.thehacker.recipes/active-directory-domain-services/movement/kerberos/shadow-credentials)

relay

### CODE REVIEW

**Comment by Startr4ck** [comment]
Really nice work!!

**Comment by ShutdownRepo** [comment]
@0xdeaddood it seems the PR was closed via something unrelated, is this an error?

**Comment by joshdodger197** [comment]
pls

**Comment by ShutdownRepo** [comment]
Closing because I messed up a few things

**Pull request closed without merging**
