### PR TITLE
wmipersist.py: Fixed filterBinding error

### PR DESCRIPTION
**Pull request by martingalloar**
As mentioned in #870 (and #787), some scenarios with `wmipersist.py` were not working, in particular, when installing a new event filter. The great @franferrax pointed out in https://github.com/SecureAuthCorp/impacket/pull/870#issuecomment-829701898 that the issue indeed was related with not explicitly setting the `filterBinding.DeliveryQoS` value, even when we want the default value to be assigned.

This PR:
* Sets the `filterBinding.DeliveryQoS` to `0` when defining the filterBinding in `wmipersist.py` example script.

### CODE REVIEW

**Comment by martingalloar** [comment]
Got this tested and working properly against Windows 10 and 2019:

Before the fix:
```
$ examples/wmipersist.py <target> install -name ASEC -vbs toexec.vbs -timer 100
[..]
[*] Adding EventFilter EF_ASEC - OK
PropName 'Filter', Value: '__EventFilter.Name="EF_ASEC"'
PropName 'Consumer', Value: 'ActiveScriptEventConsumer.Name="ASEC"'
PropName 'DeliveryQoS', Value: None
PropName 'DeliverSynchronously', Value: None
PropName 'MaintainSecurityContext', Value: None
PropName 'SlowDownProviders', Value: None
PropName 'CreatorSID', Value: [1, 2, 0, 0, 0, 0, 0, 5, 32, 0, 0, 0, 32, 2, 0, 0]
[-] Adding FilterToConsumerBinding - ERROR (0x-7ffbeff1)
```

After the fix:
```
$ examples/wmipersist.py <target> install -name ASEC -vbs toexec.vbs -timer 100
[..]
[*] Adding EventFilter EF_ASEC - OK
PropName 'Filter', Value: '__EventFilter.Name="EF_ASEC"'
PropName 'Consumer', Value: 'ActiveScriptEventConsumer.Name="ASEC"'
PropName 'DeliveryQoS', Value: 0
PropName 'DeliverSynchronously', Value: None
PropName 'MaintainSecurityContext', Value: None
PropName 'SlowDownProviders', Value: None
PropName 'CreatorSID', Value: [1, 2, 0, 0, 0, 0, 0, 5, 32, 0, 0, 0, 32, 2, 0, 0]
[*] Adding FilterToConsumerBinding - OK
```

**Comment by asolino** [comment]
Great to know it worked! @franferrax you saved us a lot of time spotting this issue. 👍

**Review by 0xdeaddood — APPROVED** [review]

**Comment by franferrax** [comment]
Hi guys, you are welcome! I'm glad to know that our findings helped you!

Just in case, regardless of the fact that the error is no longer being triggered, have you checked if the consummer script is actually being executed?

We haven't managed to get it to work in our side yet (our code is a bit different from `examples/wmipersist.py`). After setting `DeliveryQoS`, we see a binding entry in the target (by executing `wmic /NAMESPACE:"\\root\subscription" PATH __FilterToConsumerBinding get/FORMAT:list`), but the persistence script isn't being executed.

I'll come back with more information if we end up finding something that can also affect `examples/wmipersist.py`.

**Comment by franferrax** [comment]
FYI: the error that was being triggered is [`WBEM_E_INVALID_OBJECT (0x8004100F)`](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wmi/a2899649-a5a3-4b13-9ffa-d8394dcdac63#:~:text=WBEM_E_INVALID_OBJECT%3A,information%2E). `0x8004100F` is the unsigned interpretation of `-0x7FFBEFF1`, the error that you were getting in `examples/wmipersist.py`:
```
[-] Adding FilterToConsumerBinding - ERROR (0x-7ffbeff1)
```

We could get a more meaningful error by implementing [checkError()](../blob/1b9f21353fcdd3ccf0bac692bcd21375244baae0/examples/wmipersist.py#L71-L76) like this:
```python
    @staticmethod
    def checkError(banner, resp):
        call_status = resp.GetCallStatus(0) & 0xffffffff  # interpret as unsigned
        if call_status != 0:
            from impacket.dcerpc.v5.dcom.wmi import WBEMSTATUS
            try:
                error_name = WBEMSTATUS.enumItems(call_status).name
            except ValueError:
                error_name = 'Unknown'
            logging.error('%s - ERROR: %s (0x%08x)' % (banner, error_name, call_status))
        else:
            logging.info('%s - OK' % banner)
```

That would have printed the following instead:
```
[-] Adding FilterToConsumerBinding - ERROR: WBEM_E_INVALID_OBJECT (0x8004100f)
```

**Pull request merged**
