### PR TITLE
AddComputer: new example script

### PR DESCRIPTION
**Pull request by jagotu**
AddComputer.py can add a computer to a domain using LDAP or SAMR (SMB)

### CODE REVIEW

**Comment by jagotu** [comment]
I was using it in Python3, so not sure about the 2.7.

**Comment by jagotu** [comment]
@asolino Could you be more specific? The script works for me on python2 (both SAMR and LDAP).

**Comment by asolino** [comment]
Hey @jagotu 

Yes:
```
$ pythonw --version
Python 2.7.10
$ pythonw addcomputer.py 
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

Traceback (most recent call last):
  File "addcomputer.py", line 614, in <module>
    parser.print_help()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 333, in _format_usage
    assert ' '.join(pos_parts) == pos_usage
AssertionError
```
Problem seems to be related to [this](https://github.com/SecureAuthCorp/impacket/pull/667/files#diff-5e09a2e3cc6769fcfb413ca1adf6f9f7R570) line, specifically with the `metavar` definition. If I remove it, stuff seems to work.

**Comment by jagotu** [comment]
That's a bug that was fixed in June 2018: https://bugs.python.org/issue11874
It works correctly on latest 2.7 (2.7.16).

**Comment by asolino** [comment]
Thanks for the link @jagotu. Good to know it got fixed. However, AFAIK python `2.7.10` is the default 2.x install under macOS (correct me if I'm wrong). I wouldn't like users to perform an upgrade for something that could trivially be fixed.  So yeah, a workaround would be appreciated.
Are you seeing any issue on removing `metavar` for that entry and add that text under the `help` section?

**Comment by asolino** [comment]
Any news here @jagotu?

**Comment by jagotu** [comment]
@asolino Sorry for the delay.

`metavar` is better, as it shows up in the usage line, as opposed to just showing in the full help.
I added a workaround that decides based on the python version that should hopefully solve this.

**Comment by jagotu** [comment]
@asolino any updates?

**Comment by jagotu** [comment]
@asolino Any news here? Can I help somehow?

**Comment by asolino** [comment]
Sorry for the delay @jagotu. Still need to review this. Working on it hopefully next week.

**Comment by asolino** [comment]
Hey @jagotu 

While testing this over SMB I see the machine account being created but disabled by default. Are you experiencing the same?

**Comment by mubix** [comment]
> Hey @jagotu
> 
> While testing this over SMB I see the machine account being created but disabled by default. Are you experiencing the same?

Did ya'll ever figure this out?

**Comment by jagotu** [comment]
@mubix I never experienced this myself, so I have no way to debug it unfortunately.

If anyone could reproduce it on a test domain and provide a PCAP of the unsuccesful add, we might learn more.

**Pull request merged**
