### PR TITLE
Added Get-GPPPassword

### PR DESCRIPTION
**Pull request by ShutdownRepo**
Added Get-GPPPassword in examples. It's a python script for extracting and decrypting Group Policy Preferences passwords using streams for treating files instead of mounting shares, allowing for running this script inside regular docker containers. This also allows for pass-the-hash, pass-the-ticket, pass-the-key, overpass-the-hash, features that the Metasploit Framework doesn't offer.

:arrow_right: for those wondering, read this: [what are GPP Passwords](https://www.thehacker.recipes/active-directory-domain-services/movement/credentials/dumping/group-policies-preferences)

### CODE REVIEW

**Review by 0xdeaddood — CHANGES_REQUESTED** [review]
Hi @ShutdownRepo!
This is a great addition! 

I have a couple of comments before merging it: 
- Some days ago, we refactored the target parsing functions. I made some changes in the script to use these new ones.
- In the example, you are using the _chardet_ module that is not included as a requirement in impacket. We prefer not to add new modules to the project, so we wonder if there is a way to avoid its use or replace it with a built-in module (e.g. xml.etree.ElementTree). Do you see this feasible?

**Comment by ShutdownRepo** [comment]
Thank you for reviewing this :smiley: 
The new `utils` functions are great, thanks for this!
However, the `chardet` is needed to detect encoding and allow for the main "big plus" behind Get-GPPPassword.py which is searching for cpasswords without having to mount any share. We didn't manage to find any alternative lib that's already in the requirements. I think adding this lib will be really useful (it's also used in #1019), and it's quite light too. What do you think?

**Comment by 0xdeaddood** [comment]
Hey @ShutdownRepo!
Thanks again for the PR! We took some time to define if we included `chardet`... Merging!

**Comment by ShutdownRepo** [comment]
Awesome! Thank you

**Pull request merged**
