### PR TITLE
added kirbi format

### PR DESCRIPTION
**Pull request by Zer1t0**
I added a few methods into CCache class to import/export kirbi (KRB-CRED) formatted tickets. Moreover an example which converts kirbi into ccache and vice versa was also added.

### CODE REVIEW

**Comment by asolino** [comment]
hey @Zer1t0 

Great addition! Did you test it under Python3?

**Comment by asolino** [comment]
Any news here @Zer1t0? Would love to merge this.

**Comment by Zer1t0** [comment]
Done, I have to do some little changes in order to make it compatible with Python3 (adding parenthesis in print's), but it finally works. I'm glad you like the addition :).

**Comment by Zer1t0** [comment]
Hello, any news here?

**Comment by asolino** [comment]
Hey man.. sorry for the delay.. I'm merging this one, but changing the name to `ticketConverter.py`. Thanks a lot for your contribution and sorry for the delay. 

Still need to look into the other PR, especially the `features` requirement.

Thanks also @0xdeaddood for helping testing this PR.

**Pull request merged**
